INSERT INTO TB_BLOG_POST (POST_ID, CATG_ID, POST_TITL, POST_CN, READ_CNT, CRE_USR_ID, CRE_DTTM, MOD_USR_ID, MOD_DTTM) 
VALUES (1, 1, '제목1입니다', '내용1입니다. ', 1, 'ADMIN', CURRENT_TIMESTAMP, 'ADMIN', CURRENT_TIMESTAMP);
INSERT INTO TB_BLOG_POST(POST_ID, CATG_ID, POST_TITL, POST_CN, READ_CNT, CRE_USR_ID, CRE_DTTM, MOD_USR_ID, MOD_DTTM) 
VALUES (2, 1, '제목2입니다', '내용2입니다. ', 1, 'ADMIN', CURRENT_TIMESTAMP, 'ADMIN', CURRENT_TIMESTAMP);
INSERT INTO TB_BLOG_POST(POST_ID, CATG_ID, POST_TITL, POST_CN, READ_CNT, CRE_USR_ID, CRE_DTTM, MOD_USR_ID, MOD_DTTM) 
VALUES (3, 1, '제목3입니다', '내용3입니다. ', 1, 'ADMIN', CURRENT_TIMESTAMP, 'ADMIN', CURRENT_TIMESTAMP);

INSERT INTO TB_COMM_SQNO (SQNO_NM, SQNO_VL) VALUES ('POST', 1);
INSERT INTO TB_COMM_SQNO (SQNO_NM, SQNO_VL) VALUES ('MENU', 1);
COMMIT;

SELECT A.*, DATE_FORMAT(A.MOD_DTTM,'%Y%m%d%H%i%s') as modDttm FROM TB_BLOG_POST A;

INSERT INTO TB_COMM_MENU (MENU_ID, MENU_PID, QUICK_ID, MENU_NM, LVL_NO, SRT_NO, CRE_USR_ID, CRE_DTTM, MOD_USR_ID, MOD_DTTM)
VALUES ('1', '0', '', '블로그', 1, 1, 'ADMIN', CURRENT_TIMESTAMP, 'ADMIN', CURRENT_TIMESTAMP);
INSERT INTO TB_COMM_MENU (MENU_ID, MENU_PID, QUICK_ID, MENU_NM, LVL_NO, SRT_NO, CRE_USR_ID, CRE_DTTM, MOD_USR_ID, MOD_DTTM)
VALUES ('2', '0', '', '일정', 1, 2, 'ADMIN', CURRENT_TIMESTAMP, 'ADMIN', CURRENT_TIMESTAMP);
INSERT INTO TB_COMM_MENU (MENU_ID, MENU_PID, QUICK_ID, MENU_NM, LVL_NO, SRT_NO, CRE_USR_ID, CRE_DTTM, MOD_USR_ID, MOD_DTTM)
VALUES ('3', '0', '', '시스템관리', 1, 3, 'ADMIN', CURRENT_TIMESTAMP, 'ADMIN', CURRENT_TIMESTAMP);
INSERT INTO TB_COMM_MENU (MENU_ID, MENU_PID, QUICK_ID, MENU_NM, LVL_NO, SRT_NO, CRE_USR_ID, CRE_DTTM, MOD_USR_ID, MOD_DTTM)
VALUES ('4', '3', '', '메뉴', 2, 4, 'ADMIN', CURRENT_TIMESTAMP, 'ADMIN', CURRENT_TIMESTAMP);
INSERT INTO TB_COMM_MENU (MENU_ID, MENU_PID, QUICK_ID, MENU_NM, LVL_NO, SRT_NO, CRE_USR_ID, CRE_DTTM, MOD_USR_ID, MOD_DTTM)
VALUES ('5', '3', '', '사용자', 2, 5, 'ADMIN', CURRENT_TIMESTAMP, 'ADMIN', CURRENT_TIMESTAMP);
COMMIT;

INSERT INTO TB_COMM_USER (USER_ID, USER_NM, LGON_PWD)
VALUES ('ADMIN', '관리자', '');
COMMIT;
